# Generated by Django 4.2 on 2023-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0002_auditlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=90),
        ),
    ]
